CREATE TABLE "Users" (
  "UserId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" varchar(100),
  "LastName" varchar(100),
  "Email" varchar(255) UNIQUE,
  "NormalizedEmail" varchar(255) UNIQUE,
  "PasswordHash" varchar(255),
  "PhoneNumber" varchar(10),
  "AvatarKey" varchar(500),
  "DateOfBirth" timestamp,
  "IsMale" bool DEFAULT true,
  "Balance" decimal(18,2),
  "Status" int,
  "EmailVerified" bool DEFAULT false,
  "CurrentTeacherSubscriptionId" int,
  "CreatedAt" timestamp,
  "UpdatedAt" timestamp
);

CREATE TABLE "Roles" (
  "RoleId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(50) UNIQUE
);

CREATE TABLE "UserRoles" (
  "UserId" int,
  "RoleId" int,
  PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE "Permissions" (
  "PermissionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(100) UNIQUE,
  "DisplayName" varchar(200),
  "Description" varchar(500),
  "Category" varchar(50)
);

CREATE TABLE "RolePermissions" (
  "RoleId" int,
  "PermissionId" int,
  PRIMARY KEY ("RoleId", "PermissionId")
);

CREATE TABLE "ExternalLogins" (
  "ExternalLoginId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "Provider" varchar(50),
  "ProviderUserId" varchar(255),
  "ProviderDisplayName" varchar(255),
  "ProviderPhotoUrl" varchar(500),
  "ProviderEmail" varchar(255),
  "CreatedAt" timestamp,
  "LastUsedAt" timestamp
);

CREATE TABLE "RefreshTokens" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "Token" varchar(500),
  "ExpiresAt" timestamp,
  "CreatedAt" timestamp,
  "IsRevoked" bool DEFAULT false
);

CREATE TABLE "PasswordResetTokens" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "Token" varchar(500),
  "ExpiresAt" timestamp,
  "CreatedAt" timestamp,
  "IsUsed" bool DEFAULT false
);

CREATE TABLE "EmailVerificationTokens" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "Email" varchar(255),
  "OtpCode" varchar(10),
  "ExpiresAt" timestamp,
  "CreatedAt" timestamp,
  "IsUsed" bool DEFAULT false
);

CREATE TABLE "Courses" (
  "CourseId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TeacherId" int,
  "Title" varchar(255),
  "DescriptionMarkdown" text,
  "ImageKey" varchar(500),
  "ImageType" varchar(100),
  "Type" int,
  "Status" int,
  "Price" decimal(18,2),
  "ClassCode" varchar(20),
  "CreatedAt" timestamp
);

CREATE TABLE "Lessons" (
  "LessonId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CourseId" int,
  "Title" varchar(255),
  "Description" varchar(200),
  "ImageKey" varchar(500),
  "ImageType" varchar(100),
  "OrderIndex" int,
  "CreatedAt" timestamp,
  "UpdatedAt" timestamp
);

CREATE TABLE "Modules" (
  "ModuleId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "LessonId" int,
  "Name" varchar(255),
  "Description" varchar(200),
  "ImageKey" varchar(500),
  "ImageType" varchar(100),
  "ContentType" int,
  "OrderIndex" int,
  "CreatedAt" timestamp,
  "UpdatedAt" timestamp
);

CREATE TABLE "Lectures" (
  "LectureId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ModuleId" int,
  "ParentLectureId" int,
  "Title" varchar(255),
  "NumberingLabel" varchar(20),
  "Type" int,
  "MarkdownContent" text,
  "MediaKey" varchar(500),
  "MediaType" varchar(100),
  "OrderIndex" int,
  "CreatedAt" timestamp,
  "UpdatedAt" timestamp
);

CREATE TABLE "UserCourses" (
  "UserCourseId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "CourseId" int,
  "PaymentId" int,
  "JoinedAt" timestamp
);

CREATE TABLE "Assessments" (
  "AssessmentId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ModuleId" int,
  "Title" varchar(255),
  "Description" varchar(2000)
);

CREATE TABLE "Quizzes" (
  "QuizId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AssessmentId" int,
  "Title" varchar(255),
  "Description" varchar(2000),
  "Instructions" varchar(2000),
  "TotalPossibleScore" decimal(18,2)
);

CREATE TABLE "QuizSections" (
  "QuizSectionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QuizId" int,
  "Title" varchar(255),
  "Description" varchar(1000)
);

CREATE TABLE "QuizGroups" (
  "QuizGroupId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QuizSectionId" int,
  "Name" varchar(255),
  "Title" varchar(255),
  "Description" varchar(1000),
  "ImgKey" varchar(500),
  "VideoKey" varchar(500),
  "DisplayOrder" int
);

CREATE TABLE "Questions" (
  "QuestionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QuizSectionId" int,
  "QuizGroupId" int,
  "StemText" text,
  "StemHtml" text,
  "Points" decimal(18,2),
  "Type" int,
  "CorrectAnswersJson" text,
  "Explanation" text,
  "MediaKey" varchar(500),
  "MetadataJson" text,
  "DisplayOrder" int
);

CREATE TABLE "AnswerOptions" (
  "OptionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QuestionId" int,
  "Text" text,
  "IsCorrect" bool,
  "MediaKey" varchar(500),
  "Feedback" text
);

CREATE TABLE "Essays" (
  "EssayId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AssessmentId" int,
  "Title" varchar(255),
  "Description" varchar(2000),
  "AudioKey" varchar(500),
  "ImageKey" varchar(500)
);

CREATE TABLE "QuizAttempts" (
  "AttemptId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "QuizId" int,
  "TotalScore" decimal(18,2),
  "ScoresJson" text,
  "AnswersJson" text
);

CREATE TABLE "EssaySubmissions" (
  "SubmissionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "EssayId" int,
  "GradedByTeacherId" int,
  "TextContent" text,
  "AttachmentKey" varchar(500),
  "TeacherFeedback" text
);

CREATE TABLE "CourseProgresses" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "CourseId" int,
  "ProgressPercentage" float,
  "LastAccessedAt" timestamp
);

CREATE TABLE "LessonCompletions" (
  "LessonCompletionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "LessonId" int,
  "CompletionPercentage" float,
  "IsCompleted" bool,
  "VideoProgressPercentage" float,
  "LastWatchedPositionSeconds" int,
  "TotalTimeSpentSeconds" int,
  "StartedAt" timestamp,
  "CompletedAt" timestamp,
  "CompletedModules" int,
  "TotalModules" int
);

CREATE TABLE "ModuleCompletions" (
  "ModuleCompletionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ModuleId" int,
  "UserId" int,
  "IsCompleted" bool,
  "ProgressPercentage" decimal,
  "StartedAt" timestamp,
  "CompletedAt" timestamp
);

CREATE TABLE "Payments" (
  "PaymentId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "OrderCode" bigint UNIQUE,
  "IdempotencyKey" varchar(100),
  "Gateway" int,
  "Amount" decimal(18,2),
  "Status" int,
  "Description" varchar(500),
  "ProviderTransactionId" varchar(255),
  "CreatedAt" timestamp
);

CREATE TABLE "PaymentWebhookQueues" (
  "WebhookId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PaymentId" int,
  "OrderCode" bigint,
  "WebhookData" text,
  "Signature" varchar(500),
  "Status" int,
  "RetryCount" int,
  "CreatedAt" timestamp
);

CREATE TABLE "WalletTransactions" (
  "WalletTransactionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "Amount" decimal(18,2),
  "BalanceBefore" decimal(18,2),
  "BalanceAfter" decimal(18,2),
  "Type" int,
  "Description" varchar(500),
  "ReferenceId" varchar(100),
  "CreatedAt" timestamp
);

CREATE TABLE "TeacherPackages" (
  "TeacherPackageId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PackageName" varchar(100),
  "Price" decimal(18,2)
);

CREATE TABLE "TeacherSubscriptions" (
  "TeacherSubscriptionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "TeacherPackageId" int,
  "PaymentId" int
);

CREATE TABLE "CourseKnowledges" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CourseId" int UNIQUE,
  "MarkdownContent" text,
  "ContentHash" varchar(64),
  "Embedding" vector(3072)
);

CREATE TABLE "PolicyKnowledges" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PolicyId" int UNIQUE,
  "MarkdownContent" text,
  "Embedding" vector(3072)
);

CREATE TABLE "TeacherPackageKnowledges" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TeacherPackageId" int UNIQUE,
  "MarkdownContent" text,
  "Embedding" vector(3072)
);

CREATE TABLE "Policies" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Slug" varchar(255) UNIQUE,
  "Title" varchar(255),
  "ContentMarkdown" text
);

CREATE TABLE "FlashCards" (
  "FlashCardId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ModuleId" int,
  "Word" varchar(255),
  "Meaning" varchar(500),
  "Pronunciation" varchar(100),
  "Example" text,
  "CreatedAt" timestamp
);

CREATE TABLE "FlashCardReviews" (
  "UserId" int,
  "FlashCardId" int,
  PRIMARY KEY ("UserId", "FlashCardId")
);

CREATE TABLE "PronunciationProgresses" (
  "UserId" int,
  "FlashCardId" int,
  "Score" float,
  PRIMARY KEY ("UserId", "FlashCardId")
);

CREATE TABLE "Streaks" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "CurrentStreak" int,
  "LongestStreak" int,
  "LastActivityDate" timestamp
);

CREATE TABLE "Notifications" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "Title" varchar(200),
  "Message" varchar(1000),
  "Type" int,
  "IsRead" bool DEFAULT false,
  "CreatedAt" timestamp
);

CREATE TABLE "ActivityLogs" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "Action" varchar(255),
  "CreatedAt" timestamp
);

CREATE TABLE "AssetsFrontend" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NameImage" varchar(255),
  "KeyImage" varchar(500),
  "AssetType" int,
  "CreatedAt" timestamp
);

ALTER TABLE "UserRoles" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserRoles" ADD FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RolePermissions" ADD FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RolePermissions" ADD FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("PermissionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ExternalLogins" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RefreshTokens" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PasswordResetTokens" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "EmailVerificationTokens" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Courses" ADD FOREIGN KEY ("TeacherId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserCourses" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserCourses" ADD FOREIGN KEY ("CourseId") REFERENCES "Courses" ("CourseId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserCourses" ADD FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("PaymentId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Lessons" ADD FOREIGN KEY ("CourseId") REFERENCES "Courses" ("CourseId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Modules" ADD FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("LessonId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Lectures" ADD FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Lectures" ADD FOREIGN KEY ("ParentLectureId") REFERENCES "Lectures" ("LectureId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Assessments" ADD FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Quizzes" ADD FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("AssessmentId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QuizSections" ADD FOREIGN KEY ("QuizId") REFERENCES "Quizzes" ("QuizId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QuizGroups" ADD FOREIGN KEY ("QuizSectionId") REFERENCES "QuizSections" ("QuizSectionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Questions" ADD FOREIGN KEY ("QuizSectionId") REFERENCES "QuizSections" ("QuizSectionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Questions" ADD FOREIGN KEY ("QuizGroupId") REFERENCES "QuizGroups" ("QuizGroupId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AnswerOptions" ADD FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("QuestionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Essays" ADD FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("AssessmentId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QuizAttempts" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QuizAttempts" ADD FOREIGN KEY ("QuizId") REFERENCES "Quizzes" ("QuizId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "EssaySubmissions" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "EssaySubmissions" ADD FOREIGN KEY ("EssayId") REFERENCES "Essays" ("EssayId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "EssaySubmissions" ADD FOREIGN KEY ("GradedByTeacherId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "LessonCompletions" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "LessonCompletions" ADD FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("LessonId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ModuleCompletions" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ModuleCompletions" ADD FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CourseProgresses" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CourseProgresses" ADD FOREIGN KEY ("CourseId") REFERENCES "Courses" ("CourseId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Payments" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PaymentWebhookQueues" ADD FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("PaymentId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WalletTransactions" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeacherSubscriptions" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeacherSubscriptions" ADD FOREIGN KEY ("TeacherPackageId") REFERENCES "TeacherPackages" ("TeacherPackageId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeacherSubscriptions" ADD FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("PaymentId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Users" ADD FOREIGN KEY ("CurrentTeacherSubscriptionId") REFERENCES "TeacherSubscriptions" ("TeacherSubscriptionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Courses" ADD FOREIGN KEY ("CourseId") REFERENCES "CourseKnowledges" ("CourseId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeacherPackages" ADD FOREIGN KEY ("TeacherPackageId") REFERENCES "TeacherPackageKnowledges" ("TeacherPackageId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Policies" ADD FOREIGN KEY ("Id") REFERENCES "PolicyKnowledges" ("PolicyId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FlashCards" ADD FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FlashCardReviews" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FlashCardReviews" ADD FOREIGN KEY ("FlashCardId") REFERENCES "FlashCards" ("FlashCardId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PronunciationProgresses" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PronunciationProgresses" ADD FOREIGN KEY ("FlashCardId") REFERENCES "FlashCards" ("FlashCardId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Streaks" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Notifications" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ActivityLogs" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;
