CREATE TABLE "Users" (
  "UserId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "FirstName" varchar(100),
  "LastName" varchar(100),
  "Email" varchar(255),
  "PasswordHash" varchar(255),
  "Balance" decimal(18,2),
  "Status" int,
  "CurrentTeacherSubscriptionId" int,
  "CreatedAt" timestamp
);

CREATE TABLE "Roles" (
  "RoleId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(50)
);

CREATE TABLE "UserRoles" (
  "UserId" int,
  "RoleId" int,
  PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE "Permissions" (
  "PermissionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(100),
  "Category" varchar(50)
);

CREATE TABLE "RolePermissions" (
  "RoleId" int,
  "PermissionId" int,
  PRIMARY KEY ("RoleId", "PermissionId")
);

CREATE TABLE "Courses" (
  "CourseId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TeacherId" int,
  "Title" varchar(255),
  "Type" int,
  "Status" int,
  "Price" decimal(18,2),
  "ClassCode" varchar(20)
);

CREATE TABLE "Lessons" (
  "LessonId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CourseId" int,
  "Title" varchar(255),
  "OrderIndex" int
);

CREATE TABLE "Modules" (
  "ModuleId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "LessonId" int,
  "Name" varchar(255),
  "OrderIndex" int
);

CREATE TABLE "Lectures" (
  "LectureId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ModuleId" int,
  "ParentLectureId" int,
  "Title" varchar(255),
  "OrderIndex" int
);

CREATE TABLE "UserCourses" (
  "UserId" int,
  "CourseId" int,
  "PaymentId" int,
  PRIMARY KEY ("UserId", "CourseId")
);

CREATE TABLE "Assessments" (
  "AssessmentId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ModuleId" int,
  "Title" varchar(255)
);

CREATE TABLE "Quizzes" (
  "QuizId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AssessmentId" int,
  "Title" varchar(255),
  "TotalPossibleScore" decimal(18,2)
);

CREATE TABLE "QuizSections" (
  "QuizSectionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QuizId" int,
  "Title" varchar(255)
);

CREATE TABLE "QuizGroups" (
  "QuizGroupId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QuizSectionId" int,
  "Title" varchar(255),
  "DisplayOrder" int
);

CREATE TABLE "Questions" (
  "QuestionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QuizSectionId" int,
  "QuizGroupId" int,
  "StemText" text,
  "Points" decimal(18,2),
  "Type" int
);

CREATE TABLE "AnswerOptions" (
  "OptionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "QuestionId" int,
  "Text" text,
  "IsCorrect" bool
);

CREATE TABLE "Essays" (
  "EssayId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "AssessmentId" int,
  "Title" varchar(255)
);

CREATE TABLE "QuizAttempts" (
  "AttemptId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "QuizId" int,
  "TotalScore" decimal(18,2)
);

CREATE TABLE "EssaySubmissions" (
  "SubmissionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "EssayId" int,
  "GradedByTeacherId" int,
  "TextContent" text
);

CREATE TABLE "CourseProgresses" (
  "UserId" int,
  "CourseId" int,
  "ProgressPercentage" float,
  PRIMARY KEY ("UserId", "CourseId")
);

CREATE TABLE "LessonCompletions" (
  "UserId" int,
  "LessonId" int,
  PRIMARY KEY ("UserId", "LessonId")
);

CREATE TABLE "ModuleCompletions" (
  "UserId" int,
  "ModuleId" int,
  PRIMARY KEY ("UserId", "ModuleId")
);

CREATE TABLE "Payments" (
  "PaymentId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "OrderCode" bigint,
  "Amount" decimal(18,2),
  "Status" int
);

CREATE TABLE "PaymentWebhookQueues" (
  "WebhookId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PaymentId" int,
  "OrderCode" bigint,
  "Status" int
);

CREATE TABLE "WalletTransactions" (
  "WalletTransactionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "Amount" decimal(18,2)
);

CREATE TABLE "TeacherPackages" (
  "TeacherPackageId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PackageName" varchar(100),
  "Price" decimal(18,2)
);

CREATE TABLE "TeacherSubscriptions" (
  "TeacherSubscriptionId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "UserId" int,
  "TeacherPackageId" int,
  "PaymentId" int
);

CREATE TABLE "CourseKnowledges" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CourseId" int UNIQUE,
  "Embedding" varchar(1000)
);

CREATE TABLE "PolicyKnowledges" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PolicyId" int UNIQUE,
  "Embedding" varchar(1000)
);

CREATE TABLE "TeacherPackageKnowledges" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TeacherPackageId" int UNIQUE,
  "Embedding" varchar(1000)
);

CREATE TABLE "Policies" (
  "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Slug" varchar(255)
);

CREATE TABLE "FlashCards" (
  "FlashCardId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ModuleId" int,
  "Word" varchar(255)
);

CREATE TABLE "FlashCardReviews" (
  "UserId" int,
  "FlashCardId" int,
  PRIMARY KEY ("UserId", "FlashCardId")
);

CREATE TABLE "PronunciationProgresses" (
  "UserId" int,
  "FlashCardId" int,
  "Score" float,
  PRIMARY KEY ("UserId", "FlashCardId")
);

CREATE TABLE "ExternalLogins" (
  "UserId" int,
  "Provider" varchar(50)
);

ALTER TABLE "UserRoles" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserRoles" ADD FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RolePermissions" ADD FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RolePermissions" ADD FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("PermissionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Courses" ADD FOREIGN KEY ("TeacherId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserCourses" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserCourses" ADD FOREIGN KEY ("CourseId") REFERENCES "Courses" ("CourseId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "UserCourses" ADD FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("PaymentId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Lessons" ADD FOREIGN KEY ("CourseId") REFERENCES "Courses" ("CourseId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Modules" ADD FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("LessonId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Lectures" ADD FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Lectures" ADD FOREIGN KEY ("ParentLectureId") REFERENCES "Lectures" ("LectureId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Assessments" ADD FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Quizzes" ADD FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("AssessmentId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QuizSections" ADD FOREIGN KEY ("QuizId") REFERENCES "Quizzes" ("QuizId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QuizGroups" ADD FOREIGN KEY ("QuizSectionId") REFERENCES "QuizSections" ("QuizSectionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Questions" ADD FOREIGN KEY ("QuizSectionId") REFERENCES "QuizSections" ("QuizSectionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Questions" ADD FOREIGN KEY ("QuizGroupId") REFERENCES "QuizGroups" ("QuizGroupId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AnswerOptions" ADD FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("QuestionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Essays" ADD FOREIGN KEY ("AssessmentId") REFERENCES "Assessments" ("AssessmentId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QuizAttempts" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QuizAttempts" ADD FOREIGN KEY ("QuizId") REFERENCES "Quizzes" ("QuizId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "EssaySubmissions" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "EssaySubmissions" ADD FOREIGN KEY ("EssayId") REFERENCES "Essays" ("EssayId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "EssaySubmissions" ADD FOREIGN KEY ("GradedByTeacherId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Payments" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PaymentWebhookQueues" ADD FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("PaymentId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeacherSubscriptions" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeacherSubscriptions" ADD FOREIGN KEY ("TeacherPackageId") REFERENCES "TeacherPackages" ("TeacherPackageId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeacherSubscriptions" ADD FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("PaymentId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Users" ADD FOREIGN KEY ("CurrentTeacherSubscriptionId") REFERENCES "TeacherSubscriptions" ("TeacherSubscriptionId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Courses" ADD FOREIGN KEY ("CourseId") REFERENCES "CourseKnowledges" ("CourseId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TeacherPackages" ADD FOREIGN KEY ("TeacherPackageId") REFERENCES "TeacherPackageKnowledges" ("TeacherPackageId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Policies" ADD FOREIGN KEY ("Id") REFERENCES "PolicyKnowledges" ("PolicyId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CourseProgresses" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CourseProgresses" ADD FOREIGN KEY ("CourseId") REFERENCES "Courses" ("CourseId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FlashCards" ADD FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("ModuleId") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ExternalLogins" ADD FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") DEFERRABLE INITIALLY IMMEDIATE;
